### ISSUE TITLE
Doubt about jrecreate.sh

### ISSUE THREAD

**Issue by jabrena** [jweijers/EV3-robots#2]
Hi @jweijers, I checked your project and I read your process and the execution of jrecreate.sh is pretty interesting. What version of Java 8, did you install in your laptop? In java 8 se and java 9 se, I didn´t see the command.

```
./jrecreate.sh 
--dest ejre-8-b132-linux-arm-sflt.tar.gz 
--profile compact2 
--vm client tar 
-czf ejre-8-b132-linux-arm-sflt ejre-8-b132-linux-arm-sflt.tar.gz
```

Can you clarify?

Cheers

Juan Antonio

**Comment by jweijers** [comment]
Hi Juan Antonio,

The jrecreate script is separate from the regular JDK you use in your system. I use Java 8 121. 

The jrecreate script is included with Java 8 SE embedded (http://www.oracle.com/technetwork/java/javase/emb8-readme-2158733.html).

The above command actually works and results in a JRE compatible with lejos.

You can download it here: http://www.oracle.com/technetwork/java/embedded/embedded-se/downloads/index.html

Cheers,

Jeroen

**Comment by jabrena** [comment]
I fixed the problem.
Many thanks for the support:

`./jrecreate.sh --dest ejre-8-b132-linux-arm-sflt.tar.gz --profile compact3 --vm all `

Related issue:
https://github.com/ev3dev-lang-java/ev3dev-lang-java/issues/368

Juan Antonio
